### ISSUE TITLE
大佬，想向你请教个问题

### ISSUE THREAD

**Issue by sringly** [axetroy/kost#7]
看你库里开源项目都是ts，想必你非常熟练了，我是个ts初学者，看了文档，但是将现有项目切换到ts还是不知道怎么下手，大佬能否指点一下

**Comment by axetroy** [comment]
我也不是什么大佬啊，关键是多看文档，多学习

**Comment by andyhu** [comment]
我昨天刚好好学了学ts，现在正在改写自己的一个开源项目到ts，我感觉不难，找几个参考项目自己撸袖子开干不会的就搜，有一两天就够了
